version: "3"

services:
  nginx:
    image: nginx:1.25.0-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro # Let's Encrypt 인증서 (읽기 전용)
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx/:/etc/nginx/conf.d/
      - ./certbot-webroot:/var/www/certbot:ro # Certbot 인증용 디렉토리
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - blue

  blue:
    image: ${DOCKER_REGISTRY}/${DOCKER_APP_NAME}:${DOCKER_IMAGE_TAG}
    container_name: ${DOCKER_APP_NAME}-blue
    restart: always
    expose:
      - 3000
    environment:
      - TZ=Asia/Seoul

  green:
    image: ${DOCKER_REGISTRY}/${DOCKER_APP_NAME}:${DOCKER_IMAGE_TAG}
    container_name: ${DOCKER_APP_NAME}-green
    restart: always
    expose:
      - 3000
    environment:
      - TZ=Asia/Seoul

  # Certbot 컨테이너 (인증서 갱신용)
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./certbot-webroot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
